"""Add payroll

Revision ID: 53bef1819025
Revises: 3b8a4efed9d4
Create Date: 2026-08-22 12:30:25.671554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53bef1819025'
down_revision: Union[str, Sequence[str], None] = '3b8a4efed9d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('basic_wage', sa.Float(), nullable=False),
    sa.Column('house_rent_allowance', sa.Float(), nullable=False),
    sa.Column('medical_allowance', sa.Float(), nullable=False),
    sa.Column('special_allowance', sa.Float(), nullable=False),
    sa.Column('provident_fund', sa.Float(), nullable=False),
    sa.Column('tax', sa.Float(), nullable=False),
    sa.Column('gross_salary', sa.Float(), nullable=False),
    sa.Column('net_salary', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'month', name='uq_payroll_user_month')
    )
    op.create_index(op.f('ix_payroll_records_month'), 'payroll_records', ['month'], unique=False)
    op.create_index(op.f('ix_payroll_records_user_id'), 'payroll_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payroll_records_user_id'), table_name='payroll_records')
    op.drop_index(op.f('ix_payroll_records_month'), table_name='payroll_records')
    op.drop_table('payroll_records')
    # ### end Alembic commands ###
