"""Add profile and salary

Revision ID: 9e1a2cc39576
Revises: 8cae90969ab2
Create Date: 2026-08-22 11:44:21.232804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e1a2cc39576'
down_revision: Union[str, Sequence[str], None] = '8cae90969ab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_infos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('monthly_wage', sa.Float(), nullable=True),
    sa.Column('yearly_wage', sa.Float(), nullable=True),
    sa.Column('working_days_per_week', sa.Integer(), nullable=True),
    sa.Column('break_time_hours', sa.Float(), nullable=True),
    sa.Column('basic_percent', sa.Float(), nullable=True),
    sa.Column('hra_percent', sa.Float(), nullable=True),
    sa.Column('medical_allowance_fixed', sa.Float(), nullable=True),
    sa.Column('standard_allowance_percent', sa.Float(), nullable=True),
    sa.Column('performance_bonus_percent', sa.Float(), nullable=True),
    sa.Column('lta_percent', sa.Float(), nullable=True),
    sa.Column('professional_tax', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('marital_status', sa.String(length=50), nullable=True),
    sa.Column('date_of_joining', sa.Date(), nullable=True),
    sa.Column('bank_details', sa.String(length=255), nullable=True),
    sa.Column('branch_number', sa.String(length=100), nullable=True),
    sa.Column('bank_account', sa.String(length=100), nullable=True),
    sa.Column('uan_no', sa.String(length=100), nullable=True),
    sa.Column('key_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profiles')
    op.drop_table('salary_infos')
    # ### end Alembic commands ###
